### ISSUE TITLE
Cant find io.github.ZJU-ACES-ISE:jacoco-integration:jar:1.0-SNAPSHOT

### ISSUE THREAD

**Issue by EsdrasCaleb** [ZJU-ACES-ISE/chatunitest-core#10]
I got this error trying to build, I am doing a research but using the version 1.1.0 because of this:
Could not resolve dependencies for project io.github.ZJU-ACES-ISE:chatunitest-core:jar:2.0.0: Could not find artifact io.github.ZJU-ACES-ISE:jacoco-integration:jar:1.0-SNAPSHOT

**Comment by coder-chenzhi** [comment]
@cube-dragon @Mikekkkkk

**Comment by cube-dragon** [comment]
@EsdrasCaleb This issue currently has a solution provided in the [README](https://github.com/ZJU-ACES-ISE/chatunitest-maven-plugin/?tab=readme-ov-file#1coverup)

**Comment by EsdrasCaleb** [comment]
> @EsdrasCaleb This issue currently has a solution provided in the [README](https://github.com/ZJU-ACES-ISE/chatunitest-maven-plugin/?tab=readme-ov-file#1coverup)

Okay sorry I cant find the link to Jacoco-integration.zop

**Comment by Mikekkkkk** [comment]
@EsdrasCaleb Two methods to resolve this problem      
1. you can pull this branch https://github.com/ZJU-ACES-ISE/chatunitest-core/commit/366f81fce04291d81961e10533fdc21d226ae0f4 
2. you can get the temporary release and install this jacoco-integration project : https://github.com/ZJU-ACES-ISE/jacoco-integration/releases/tag/jacoco
Thanks for your support for our project

**Comment by EsdrasCaleb** [comment]
oh thx I will check this

**Comment by EsdrasCaleb** [comment]
Is there any doc on how to use a local model (localhost) with it? I did some alterations in 1.1.0 to use Gemini and huggingfaces but If there is any official one would help...

**Comment by Mikekkkkk** [comment]
@EsdrasCaleb try to encapsulate your local model as an API interface in the form of openAI, which can be assisted by tools such as ollama

**Comment by EsdrasCaleb** [comment]
YEa I did it, so I just use my local as an URL of GTP, right?
Do you plan to use local models inside the core like 
https://github.com/mukel/llama3.java

Or connect to outer web models like gemini claude 

?

**Comment by Mikekkkkk** [comment]
> Well I can run now. I don't know if the local models can support so much tokens, but I know how alter it to work. How can I do it if I want to submit an update I made? I corrected some TODO and included a Timeout option in the config

@EsdrasCaleb  You can submit a Pull Request,we will check later

**Comment by EsdrasCaleb** [comment]
Yes, I am using local models so sometimes I also need the timeout to exist, because my local model takes more time to answer. Also, I need to specify the maximum token for different prompts. Eg. the Intention prompt needs less token count.

I see there are more runners than Chattester now. Is there any ref about this. Or is an unpublished article yet?
