### ISSUE TITLE
Internal class and anonymous class name conflict issue

### ISSUE THREAD

**Issue by cube-dragon** [ZJU-ACES-ISE/chatunitest-core#5]
1. Due to the current generation logic being designed to generate tests for individual methods and ultimately consolidate them into a single package, issues arise when there are test classes and enum classes with the same name.

2. Some tests generated by the LLM not only use internal classes but also external classes with the same name, leading to confusion about which class should actually be used.

3. The tests generated by the LLM attempt to throw an exception that will never be thrown.
![image](https://github.com/user-attachments/assets/f06b1497-c19d-49cb-880f-6bb21b58e8cc)

**Comment by cube-dragon** [comment]
The first issue has been resolved, and the idea is to iterate through all tests after generation and add numbering to the names of internal and enumeration classes to prevent naming conflicts

**Comment by coder-chenzhi** [comment]
This issue is addressed by PR #6
